k9s:
  liveViewAutoRefresh: true
  gpuVendors: {}
  screenDumpDir: C:\Users\duncanbeard\AppData\Local\k9s\screen-dumps
  refreshRate: 1
  apiServerTimeout: 2m0s
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  portForwardAddress: localhost
  ui:
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: false
    splashless: false
    reactive: true
    noIcons: false
    defaultsToFullScreen: true
    useFullGVRTitle: false
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 1000
    buffer: 5000
    sinceSeconds: -1
    textWrap: true
    disableAutoscroll: false
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  defaultView: ""
